name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: 
      - feat/#17-cicd
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: GGUM_Team_2_BE/ggum

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: GGUM_Team_2_BE/ggum
